### PR TITLE
Update to newest .net

### PR DESCRIPTION
**Pull request by sensslen**

### CODE REVIEW

**Comment by micdenny** [comment]
thank you for this contribution, please have a check of the failed build

**Comment by sensslen** [comment]
sorry - fixed

**Comment by micdenny** [comment]
removing `netcoreapp3.1` and `net5` support do you think it's better to bump the version to a major release 3.0.0?

**Comment by sensslen** [comment]
I would not think so - netcoreapp3.1 is out of support as well as net5.... However it's up to you to decide...

**Comment by micdenny** [comment]
In fact I didn't change any part of the public surface nor internal feature, so basically the new version is just for updating target frameworks.

I will bump the patch then, because I didn't change any feature.

**Comment by micdenny** [comment]
deployed to nuget, will be ready soon: https://www.nuget.org/packages/WpfScreenHelper/2.1.1

**Comment by sensslen** [comment]
Thanks you a lot

**Pull request merged**
