### PR TITLE
Dpi awareness support

### LINKED ISSUE #6: Dpi fix breaks support on Windows 7
The fix for DPI support breaks Windows 7.

System.DllNotFoundException: Unable to load DLL 'shcore.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

   at WpfScreenHelper.NativeMethods.GetDpiForMonitor(IntPtr hmonitor, DpiType dpiType, UInt32& dpiX, UInt32& dpiY)

   at WpfScreenHelper.Screen..ctor(IntPtr monitor, IntPtr hdc)

   at WpfScreenHelper.Screen.get_AllScreens()

### PR DESCRIPTION
**Pull request by FoxPride**
Fixes #6

### CODE REVIEW

**Comment by FoxPride** [comment]
Also fixes #9

**Comment by FoxPride** [comment]
Fix for #7 

- Removed Screen.FromWpfPoint because function was inconsistent since wpf coordinates can intersect between monitors.
- Changed back Bounds from PixelBounds and added WpfBounds instead (old bounds since v1.1.0) to be compatible with version 1.0.0.
- Added WpfWorking area.
- Added description for WindowHelper.
- Reworked SetWindowPosition function.

**Comment by FoxPride** [comment]
@micdenny can please check this pr? Fixed some bugs and reworked to be more compatbile with version 1.0.0

**Comment by micdenny** [comment]
I would declare a breaking change here isn't it? v2.0.0?

**Comment by FoxPride** [comment]
Yes, definitely version 2.0.0

**Comment by micdenny** [comment]
@FoxPride I've fixed the PR, was started from an unsquashed master, I've hard resetted the branch on the origin (micdenny) master, then cherry picked all your item where you will remain author of it.

Now the conflicts are gone, and I'm ready to review it.

**Comment by micdenny** [comment]
@FoxPride Can you confirm that what I did is fine? do you see all your changes?

**Comment by FoxPride** [comment]
@micdenny everything looks good

**Comment by micdenny** [comment]
[v2.0.0 has been released](https://www.nuget.org/packages/WpfScreenHelper/2.0.0)

**Pull request merged**
